In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("./DirtyData.csv")
df.head()

,first_name,last_name,email,gender,income,tax_15
0,Alverta,Colkett,acolkett0@cocolog-nifty.com,Female,123072.34,NaN
1,Nichole,Brandassi,nbrandassi1@mail.ru,Bigender,NaN,24115.00
2,Ruperto,Chaddock,rchaddock2@mail.ru,Male,62524.77,9378.72
3,Lula,Sorrill,lsorrill3@hatena.ne.jp,Female,48000.77,7200.12
4,Blondell,Benard,bbenard4@admin.ch,Female,88638.49,13295.77

### Step 1: Inspect the data before doing anything

In [23]:
print(df.isna().sum())
print()
print(df["gender"].value_counts())

first_name    0
last_name     0
email         0
gender        0
income        0
tax_15        0
dtype: int64

gender
Female         474
Male           422
Non-binary      21
Genderfluid     19
Polygender      18
Genderqueer     17
Bigender        16
Agender         13
Name: count, dtype: int64

### Step 2: Handle missing valeus by reconstruction

In [ ]:
# columns WHERE income is na, tax is NOT na, then grab tax * (100/15), and put that new value into income
df["income"] = np.where(df["income"].isna() & df["tax_15"].notna(), df["tax_15"]*(100/15), df["income"])

# same as above but work backwards to get tax column from income
df["tax_15"] = np.where(df["tax_15"].isna() & df["income"].notna(), df["income"]*(15/100), df["tax_15"])

### Step 3: Fix negative incomes

In [26]:
df["income"] = df["income"].abs()
df["tax_15"] = df["tax_15"].abs()

print(f"Negative incomes remaining: {(df["income"] < 0).sum()}")

Negative incomes remaining: 0

### Step 4: standardize gender with judgment

In [15]:
df["gender"].value_counts()

gender_map = {
    "Men" : "Male", "Man":"Male",
    "Woman":"Female", "Women":"Female"
}

df["gender"] = df["gender"].replace(gender_map)
df.head(20)

,first_name,last_name,email,gender,income,tax_15
0,Alverta,Colkett,acolkett0@cocolog-nifty.com,Female,123072.340000,18460.8510
1,Nichole,Brandassi,nbrandassi1@mail.ru,Bigender,160766.666667,24115.0000
2,Ruperto,Chaddock,rchaddock2@mail.ru,Male,62524.770000,9378.7200
3,Lula,Sorrill,lsorrill3@hatena.ne.jp,Female,48000.770000,7200.1200
4,Blondell,Benard,bbenard4@admin.ch,Female,88638.490000,13295.7700
5,Jacquelyn,Fawdry,jfawdry5@addthis.com,Female,96620.000000,14493.0000
6,Kurt,Dugue,kdugue6@istockphoto.com,Male,105041.020000,15756.1500
7,Cordelie,Bloxsom,cbloxsom7@state.gov,Female,236589.680000,35488.4500
8,Katinka,Renzo,krenzo8@thetimes.co.uk,Female,194301.630000,29145.2400
9,Ketty,Pakeman,kpakeman9@chicagotribune.com,Female,239219.050000,35882.8575
10,Nicky,Cooley,ncooleya@mayoclinic.com,Genderfluid,220441.770000,33066.2700
11,Tarrah,Boot,tbootb@joomla.org,Female,103297.250000,15494.5900
12,Bert,Edmondson,bedmondsonc@usatoday.com,Male,217100.070000,32565.0105
13,Carlotta,Franzoli,cfranzolid@jiathis.com,Female,194280.000000,29142.0000
14,Ryan,Densumbe,rdensumbee@cyberchimps.com,Male,138737.320000,20810.6000
15,Jill,Minthorpe,jminthorpef@blinklist.com,Female,-101308.010000,15196.2000
16,Christiano,Calow,ccalowg@surveymonkey.com,Male,61107.210000,9166.0800
17,Ame,Ambrozewicz,aambrozewiczh@ihg.com,Female,33310.480000,4996.5700
18,Leena,Fellgett,lfellgetti@slate.com,Female,138446.690000,20767.0000
19,Coralyn,Stockey,cstockeyj@typepad.com,Female,-89765.700000,-13464.8550

### Step 5: Normalize Income (min-max)

In [27]:
_min = df["income"].min()
_max = df["income"].max()

income_range = (_max - _min)
df["income_norm"] = (df["income"] - _min) / income_range

### Step 6: Final check and save

In [28]:
df.to_csv("./CleanData.csv", index= False)

## In class Activity
1. print the 5-num summary of cleaned income column
2. how many ppl are in eaach gender category after cleaning?

- git add yourfile
- git commit -m "message"
- git push -u origin main

In [29]:
# 1. print 5-num summary
def fns(column):
    #find 5 num summary
    min = np.min(df[column])
    Q1 = np.percentile(df[column], 25)
    median = np.median(df[column])
    Q3 = np.percentile(df[column], 75)
    max = np.max(df[column])

    #find mean
    mean = df[column].mean()


    #Print stats
    print(f'------------ FNS for {column.capitalize()} -------------')
    print(f"Min: {min}")
    print(f"Q1: {Q1}")
    print(f"Median: {median}")
    print(f"Q3: {Q3}")
    print(f"Max: {max}")
    print(f"Mean: {mean}")
fns("income")

# 2. how many ppl are in each gender category
print(df["gender"].value_counts())

------------ FNS for Income -------------
Min: 15245.38
Q1: 80435.7175
Median: 139509.475
Q3: 201023.5875
Max: 326986.6666666667
Mean: 140011.67146
gender
Female         474
Male           422
Non-binary      21
Genderfluid     19
Polygender      18
Genderqueer     17
Bigender        16
Agender         13
Name: count, dtype: int64